{% set name = "napari-plot-profile" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-plot-profile-{{ version }}.tar.gz
  sha256: 1a1f087b23eaa71a16f0ffde66e965fd7f6b69e5d52b3664c7db295f30fed501

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - napari
    - napari-plugin-engine >=0.1.4
    - napari-skimage-regionprops >=0.2.4
    - napari-tools-menu
    - numpy
    - pyqtgraph
    - python >={{ python_min }}

test:
  imports:
    - napari_plot_profile
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/haesleinhuepf/napari-plot-profile
  summary: Plot intensity along a line in napari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - haesleinhuepf
